version: '3.9'
services:
    stocks-io-client:
        container_name: stocks-io-client
        restart: always
        depends_on:
            - stocks-io-api
        build:
            context: client
            dockerfile: Dockerfile
        ports:
            - '3003:3000'
        environment:
            - VITE_API_URI=${VITE_API_URI}
        network_mode: bridge
    stocks-io-api:
        container_name: stocks-io-api
        restart: always
        build:
            context: server
            dockerfile: Dockerfile
        ports:
            - '3002:4000'
        environment:
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - MONGO_DB=${MONGO_DB}
            - JWT_SECRET=${JWT_SECRET}
            - FINNHUB_API_KEY=${FINNHUB_API_KEY}
        network_mode: bridge
